apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vellic
  labels:
    app.kubernetes.io/name: vellic-api
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: vellic-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
