.git
.gitignore

api
worker
admin
packages

**/.venv
**/__pycache__
**/.pytest_cache
**/*.pyc
**/*.pyo

node_modules
frontend/node_modules
frontend/.next
frontend/out

docs
*.md
.env*
Makefile

**/coverage
**/.coverage
