apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: vellic
  labels:
    app.kubernetes.io/name: vellic-admin
    app.kubernetes.io/component: admin
spec:
  selector:
    app.kubernetes.io/name: vellic-admin
  ports:
    - name: http
      port: 80
      targetPort: 8001
  type: ClusterIP
